git clone https://github.com/AleVH/Calu-Service-API-GATEWAY.git ./Code-Base/api-gateway/
git clone https://github.com/AleVH/Calu-Service-AUTH-SERVICE.git ./Code-Base/auth-service/
git clone https://github.com/AleVH/Calu-Service-CARD-SERVICE.git ./Code-Base/card-service/
git clone https://github.com/AleVH/Calu-Service-CONNECTOR-SERVICE.git ./Code-Base/connector-service/
git clone https://github.com/AleVH/Calu-Service-DUMMY-SERVICE.git ./Code-Base/dummy-service/
git clone https://github.com/AleVH/Calu-Service-FX-SERVICE.git ./Code-Base/FX-SERVICE/
git clone https://github.com/AleVH/Calu-Service-KYC-SERVICE.git ./Code-Base/KYC-SERVICE/
git clone https://github.com/AleVH/Calu-Service-PAYMENT-SERVICE.git ./Code-Base/PAYMENT-SERVICE/
git clone https://github.com/AleVH/Calu-Service-RABBITMQ-WORKER.git ./Code-Base/RABBITMQ-WORKER/
git clone https://github.com/AleVH/Calu-Service-REDIS-WORKER.git ./Code-Base/redis-worker/
git clone https://github.com/AleVH/Calu-Service-UI-ADMIN.git ./Code-Base/ui-admin/
git clone https://github.com/AleVH/Calu-Service-UI-BUSINESS.git ./Code-Base/ui-business/
git clone https://github.com/AleVH/Calu-Service-UI-CONSUMER.git ./Code-Base/ui-consumer/
git clone https://github.com/AleVH/Calu-Service-USER-SERVICE.git ./Code-Base/user-service/
